name: Deployment

on:
  push:
    branches:
      - main
      - stg
      - preprod
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . -t an6eel/gitops-seminar-code:$GITHUB_SHA

      - name: Log into registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: docker push an6eel/gitops-seminar-code:$GITHUB_SHA

  notify-update:
    needs: publish-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Project
        uses: actions/checkout@master
        with:
          repository: an6eel/gitops-seminar-infra
          token: ${{ secrets.GITOPS_TOKEN }}
          path: ./infra

      - name: Notify infra repo update
        run: |
          git config --global user.name "an6eel"
          git config --global user.email "agarciamal1997@gmail.com"
          case "${GITHUB_REF##*/}" in
            main) export REPO_PATH=prod ;;
            preprod) export REPO_PATH=preprod ;;
            stg) export REPO_PATH=stg ;;
          esac
          cd infra/resources/apps/api/$REPO_PATH
          docker run --rm -v ${PWD}:/workdir mikefarah/yq:3.2.1 yq write --inplace --verbose values.yaml api.image.tag $GITHUB_SHA
          git commit -am "Update code" && git push



